Socint 258 configure eq toke for poc
ONSdigital/sdc-int-rh-ui pull request #35
Opened 2021-11-24 16:38 UTC by SteveScorfield

# Motivation and Context
It is required as part of the upcoming POC show and tell.

# What has changed
eq.py along with tests have been updated to accept the new values required.

# Links
https://collaborate2.ons.gov.uk/jira/browse/SOCINT-258

2021-11-24 16:57 UTC, Paul-Joel approved these changes

2021-11-25 10:46 UTC, rpcatling requested changes
some comments

2021-11-25 10:46 UTC, rpcatling commented on app/eq.py
>              'user_id': self._user_id,
JIRA asks for `user_id` to be removed

2021-11-25 10:46 UTC, rpcatling commented on app/eq.py
>              'region_code': self.convert_region_code(self._region),
although the JIRA asks for `region_code` to be hardcoded, I guess it is reasonable to leave as-is ?

2021-11-25 10:46 UTC, rpcatling commented on app/eq.py
>              'language_code': self._language_code,
although the JIRA asks for region_code to be hardcoded, I guess it is reasonable to leave as-is ?

2021-11-25 10:46 UTC, rpcatling commented on app/eq.py
>              'channel': self._channel,
JIRA asks for "RH" but we are providing "rh".  Is that OK ? Needs confirmation.

2021-11-25 10:49 UTC, SteveScorfield commented on app/eq.py
>              'channel': self._channel,
Already discussed with Paul and Sam. It needs to be 'rh'.

2021-11-25 10:49 UTC, SteveScorfield commented on app/eq.py
>              'language_code': self._language_code,
As above

2021-11-25 10:51 UTC, SteveScorfield commented on app/eq.py
>              'user_id': self._user_id,
This has been crossed out in the ticket and took it to mean that this needs to stay. As in it said to be removed but then crossed out.

2021-11-25 10:53 UTC, rpcatling commented on app/eq.py
>              'channel': self._channel,
OK

2021-11-25 12:57 UTC, SteveScorfield commented on app/eq.py
>              'user_id': self._user_id,
As agreed, user_id has been removed.

2021-11-25 13:35 UTC, rpcatling approved these changes

2021-11-25 13:36 UTC, merged