Dependency upgrades
ONSdigital/sdc-int-rh-ui pull request #46
Opened 2022-05-17 07:44 UTC by KieranWardle

# Motivation and Context
The python version and most dependencies were very out of date

# What has changed
Upgraded all dependencies and the python version
Removed old directories

# How to test?
Tested through acceptance tests

# Links
https://trello.com/c/y6xA2Djt

# Screenshots (if appropriate):

2022-05-17 08:29 UTC, AdamHawtin commented on Dockerfile
> +FROM python:3.10.4
Could we swap to `python:3.10.4-slim` here? Should work as a straight swap, we've already checked it's fine on the slim image.

2022-05-17 09:03 UTC, AdamHawtin requested changes

2022-05-17 09:03 UTC, AdamHawtin commented on Pipfile
> +cchardet = "~=2.1.7"
I think `cchardet` is unused, tested locally and unit/cucumber tests pass without it

2022-05-17 09:03 UTC, AdamHawtin commented on Pipfile
> +iso8601 = "~=1.0.2"
I think `iso8601` is unused, tested locally and unit/cucumber tests pass without it

2022-05-18 10:32 UTC, AdamHawtin requested changes
Awesome work getting it all working and up to date, built and tested locally and all good 👍 

Just one bit of commented out/now dead code I think should be deleted.

2022-05-18 10:32 UTC, AdamHawtin commented on app/session.py
> +    # Session.__init__ = aiohttp_session_pr_331_rollback
Looks like we can delete this entirely now, including the function above that it was patching in. I checked the issue linked in the comment, and it's been resolved/closed for some time.

2022-05-18 11:15 UTC, AdamHawtin approved these changes

2022-05-18 14:14 UTC, hbrace approved these changes

2022-05-18 14:16 UTC, merged