Add cookies and privacy pages
ONSdigital/sdc-int-rh-ui pull request #51
Opened 2022-07-28 12:55 UTC by hbrace

# Motivation and Context

We want to be able to give information to the users about cookies and privacy/data protection
# What has changed

Cookies page added
Privacy and data protection page added
# How to test?

Build and run the service off this branch
Check that the links to cookies and the privacy/data protection pages work and take you to the correct page.
Check that the info on these pages match up with what is linked to on the card.
# Links

https://trello.com/c/w0QdMA7E/152-create-cookie-and-privacy-pages-and-provide-eq-with-links-5
# Screenshots (if appropriate):

2022-07-29 13:07 UTC, ryangrundy7 commented on app/templates/base-cy.html
> +            'secondaryButtonUrl': domain_url_cy + '/cookies',
The link is wrong on the cookie banner. Should be `/cookies/`. Wonder if we can set it so it just doesn't matter 🤔

2022-07-29 13:42 UTC, ryangrundy7 approved these changes

2022-08-01 09:55 UTC, davidmort requested changes

2022-08-01 10:26 UTC, davidmort approved these changes

2022-08-01 11:06 UTC, merged