minimal required to remove welsh routing
ONSdigital/sdc-int-rh-ui pull request #60
Opened 2022-09-09 07:06 UTC by LukeLoze1

# Motivation and Context
No Welsh routing

# What has changed
Removed cy from allowed paths, hacked out Translation option.  Fixed tests to cope with this

This was a minimal change, take 2.  The ticket leaves RH-UI even more yukky, with lots of 

if display_region = 'cy:

code still in it and Welsh templates,  they are now unused.

# How to Test
In you env with other bits from ticket, does it work as expected can you navigate to .../cy/start

# Links
[

# Screenshots (if appropriate):](https://trello.com/c/KadaIply/322-rh-english-only-routing8)

2022-09-12 08:29 UTC, AdamHawtin requested changes
I'm getting unit test failures locally. The tests don't appear to be running on/blocking PRs.

2022-09-12 08:36 UTC, AdamHawtin commented
When I try navigating to `/cy/start`, I get a 404 page but in welsh, suggests some welsh conditional routing is still happening?

2022-09-12 10:05 UTC, ryangrundy7 reviewed
From what I can see I can't access any welsh page now 👍 There's still a mention in the readme to `http://localhost:9092/cy/start/` which should be fixed

2022-09-12 10:23 UTC, ryangrundy7 approved these changes
Can't seem to route to any of the welsh links so looks good to me 👍

2022-09-13 11:51 UTC, AdamHawtin approved these changes
Works fine locally, `/cy/` routes now only get the expected `Page Not Found`.

I wonder if we need another MVP follow-up to remove `/en/` from the valid routes?

2022-09-14 07:38 UTC, merged