385 rh UI headers
ONSdigital/sdc-int-rh-ui pull request #71
Opened 2022-11-10 09:37 UTC by LukeLoze1

# Motivation and Context
Improve RH-UI headers security

# What has changed
Added some new headers

# How to test?
Does it still work, does it match the ticket?

# Links
https://trello.com/c/QxGXGtIP/385-rh-ui-headers-3

2022-11-10 15:48 UTC, hbrace approved these changes

2022-11-11 10:22 UTC, davidmort requested changes

2022-11-11 10:22 UTC, davidmort commented on app/security.py
> +    'Cache-Control': ['no-store', 'max-age=0']
```suggestion
    'Cache-Control': ['no-store', 'max-age=0'],
    'Server': 'Office For National Statistics',
```

need to set the Server header to stop exposing internal tech info

2022-11-11 10:22 UTC, davidmort commented on tests/unit/test_app.py
> +        self.assertEqual(response.headers['Cache-Control'], 'no-store max-age=0')
```suggestion
        self.assertEqual(response.headers['Cache-Control'], 'no-store max-age=0')
        self.assertEqual(response.headers['Server'], 'Office for National Statistics')
```

2022-11-11 10:28 UTC, davidmort approved these changes

2022-11-15 10:21 UTC, merged