585 Fix prod config
ONSdigital/sdc-int-rh-ui pull request #79
Opened 2022-11-28 14:44 UTC by AdamHawtin

# Motivation and Context

We want the app to default to safe config for production, and make it easier to understand how the config is set. The config template is now set by a `CONFIG_NAME` environment variable and will default to the `BaseConfig` if nothing is supplied, preventing the app from starting up with unexpected dev defaults.

Also, the "check" features of the info endpoint were broken and would fail semi silently, so I have removed the `check` parameter functionality entirely from that endpoint.

Also, while I was having to fix things across many files, I have made a start on replacing all the relatively imports with absolute.

# What has changed

- Stop the app defaulting to development/debug config
- Make the settings config clearer and more visible 
- Remove `check` parameter from the info endpoint and the unused supporting code
- Replace relative imports with absolute

# How to test?

Build locally and run in Docker dev, run the ATs, manually check the UI still appears the same.

# Links

https://trello.com/c/M2Z2vUC6/585-rh-ui-needs-to-use-prod-config-5

2022-11-29 09:35 UTC, ryangrundy7 commented on app/config.py
> +    DOMAIN_URL = env('DOMAIN_URL')
Still a few mentions of `DOMAIN_URL_EN` in the templates and other files. Worth doing that here or keeping it separate to the other card

2022-11-29 10:17 UTC, liamtoozer approved these changes
LGTM 👍

2022-11-29 16:23 UTC, ryangrundy7 requested changes
`EXT_LOG_LEVEL,LOG_LEVEL,HOST,PORT` these values need to be set for the app to come up. Might be worth checking what's actually used

2022-11-30 09:27 UTC, ryangrundy7 approved these changes

2022-11-30 09:48 UTC, merged